  version: "3.8"
  
  services:
    db-mysql:
      container_name: mysql-challenge
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ../scripts/docker.sql:/docker-entrypoint-initdb.d/docker.sql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: Dev@123
      ports:
        - 3306:3306
      networks:
        - challenge-net  

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      networks:
        - challenge-net  

    web-api:
      image: challenge-coodesh-api:latest
      container_name: challenge-coodesh-api
      build:
        context: ../src
        dockerfile: ./Coodesh.Challenge.Api/Dockerfile
      ports:
        - 5005:5005
      restart: always  
      environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://*:5005
      depends_on:
        - db-mysql
      networks:
        - challenge-net  

  networks:
   challenge-net:
      driver: bridge    